export const generalActionTypes = {
  SET_IS_APP_LOADING: "SET_IS_APP_LOADING",
  SET_TOKEN: "SET_TOKEN",
  SET_FIRST_TIME_USE: "SET_FIRST_TIME_USE",
  SET_USER_DATA: "SET_USER_DATA",
};

export const cartActionTypes = {
  GET_CART_ITEMS: "GET_CART_ITEMS",
  SET_IS_LOADING: "SET_IS_LOADING",
};
